version: "3.1"
services:
  web:
    build: .
    ports:
      - "4000:4000"
    command: mix phoenix.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/app
    depends_on:
      - db

  postgres:
    image: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db